name: Build ModernStaggerLock

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Install Ninja
      run: choco install ninja

    - name: Configure CMake
      env:
        CommonLibSSEPath: ${{ github.workspace }}/CommonLibSSE-NG
        DKUtilPath: ${{ github.workspace }}/DKUtil
        HEADLESS: 1
      run: |
        cmake -B build -S . -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows-static-md

    - name: Build
      run: cmake --build build

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ModernStaggerLock-DLL
        path: build/ModernStaggerLock.dll
